# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0ef431d237d78a786bfacb6455d7b4d7a74c80f6c5849bb49e9cddb4e0f8fe67699ac50f03c8978e2e933a0438a7ddf8c39acc63cfaf660b97f346b3e298104

test:
  secret_key_base: 182febe2bfc056dfe05f452f2c7d0b59e9f6d01889b5dfdd371c2855f5b29f3fbd6b81e61b3491f56b0fa48a0d74105ccc86a1a9c85ab1c0487785cc339008eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
